language: objective-c
node_js:
  - "4.2"
before_install:
  - npm install -g cordova
  - npm install -g ios-sim
  - npm install -g ios-deploy
  - npm install -g cordova-paramedic
install:
  - npm install
script:
  - cordova-paramedic --platform ios --plugin $(pwd) --verbose
